# Generated by Django 4.1.4 on 2022-12-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_cartorder_options_alter_cartorderitems_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotherboardAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_mother", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "link_olshop",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("img", models.CharField(blank=True, max_length=200, null=True)),
                ("brandme", models.CharField(blank=True, max_length=200, null=True)),
                ("modelme", models.CharField(blank=True, max_length=200, null=True)),
                ("formFactor", models.CharField(blank=True, max_length=200, null=True)),
                ("chipset", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "memorySlots",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("socketType", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
